version: '3.8'

services:
  # Development service
  portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8000}
      - VITE_ENVIRONMENT=development
      - VITE_APP_NAME=Portfolio
      - VITE_APP_VERSION=dev
    command: npm run dev
    
  # Production service  
  portfolio-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8000}
        - VITE_ENVIRONMENT=production
        - VITE_APP_NAME=Portfolio
        - VITE_APP_VERSION=${APP_VERSION:-latest}
    ports:
      - "8080:8080"
    environment:
      - API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s