name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'

jobs:
  # Code quality checks
  lint:
    name: Code Quality & Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
          
      - name: Run ESLint (JavaScript only)
        run: npm run lint
        continue-on-error: true
        
      - name: Check TypeScript compilation
        run: npx tsc --noEmit

  # Security audit
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
          
      - name: Run npm audit
        run: npm audit --audit-level moderate
        continue-on-error: true
        
      - name: Run security scan with njsscan
        uses: ajinabraham/njsscan-action@v7
        with:
          args: '--sarif --output results.sarif src/ || true'
          
  # Test job
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
          
      - name: Install additional test dependencies
        run: npm install --save-dev jsdom @testing-library/react @testing-library/jest-dom
        
      - name: Run tests
        run: npm test
        
      - name: Generate coverage report
        run: npm run coverage
        continue-on-error: true
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          fail_ci_if_error: false

  # Notification job
  notify:
    name: Notify Results
    runs-on: ubuntu-latest
    needs: [lint, test, security]
    if: always()
    steps:
      - name: Notify success
        if: needs.lint.result == 'success' && needs.test.result == 'success' && needs.security.result == 'success'
        run: echo "✅ Pipeline completed successfully"
        
      - name: Notify failure
        if: needs.lint.result == 'failure' || needs.test.result == 'failure' || needs.security.result == 'failure'
        run: echo "❌ Pipeline failed - check logs for details"